### ISSUE TITLE
Support build Lambda Collector extension layer on demand

### ISSUE THREAD

**Issue by wangzlei** [open-telemetry/opentelemetry-lambda#100]
At the moment Lambda Collector extension layer contains [very limit components](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/collector/lambdacomponents/default.go#L20-L23) due to the the reason described [here](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/docs/design_proposal.md#22-memory-consumption).

Adding more collector components into code is cautious because we don't want to inflate the binary size, and also for neutrality we suggest Vendor maintains its downstream repo. For example [ aws-otel-lambda](https://github.com/aws-observability/aws-otel-lambda) contains AWS XRay exporter and EMF exporter.

Ideally, we want to provide a mechanism to let user easily build a custom collector extension layer based on his demand. Here give an option by using [opentelemetry-collector-builder](https://github.com/open-telemetry/opentelemetry-collector-builder), so user can dynamically build and publish custom lambda layer to his individul AWS account:
1. download this repo
2. go to `collector` folder
3. create his Collector config custom.yml under folder `collector`
4. run `make publishpublish-layer`

**Comment by dglozano** [comment]
Is there any time estimate on this or possible workaround until it's resolved? We would love to use open telemetry in our lambdas and send traces to Datadog, but the only way to do that it seems to be by using the datadog exporter in the collector, which is not included in the layer version of it
