### ISSUE TITLE
Missing the Attributors Processor

### ISSUE THREAD

**Issue by matheuscanela** [open-telemetry/opentelemetry-lambda#102]
Tried to use attribute processor and it doesn't seem to be compatible with Lambda/Node JS layer.

I tested the two configuration files below, but they didn't work. Is it possible to add to Lambda layer?

**References:**
https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/README.md#general-information
https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/attributesprocessor

**Codes and Errors:**
Error: Error: cannot load configuration: unknown processors type "attributes" for attributes

```receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  awsxray:
    index_all_attributes: true
    
processors:
  attributes:
    exclude:
      match_type: strict
      attributes:
        - key: otel_resource_process_executable_name

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: 
      - attributes
      exporters: [logging, awsxray]
    metrics:
      receivers: [otlp]
      exporters: [logging]
```

Error: Error: cannot load configuration: unknown processors type "attributes" for attributes/delete

```receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: debug
  awsxray:
    index_all_attributes: true
    
processors:
  attributes/delete:
    actions:
      - key: otel_resource_process_executable_name
        action: delete

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes/delete]
      exporters: [logging, awsxray]
    metrics:
      receivers: [otlp]
      exporters: [logging]```

**Comment by anuraaga** [comment]
@wangzlei I think we should add all the processors except for batchprocessor from core

https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor

They seem like they should have a very small effect on binary size. The most important though are attributes, memorylimiter, resource, span processors.

**Comment by matheuscanela** [comment]
Thanks @anuraaga 
They are really important as customers would like to remove PII data, which is not possible without the processor - am I right?

**Comment by wangzlei** [comment]
@anuraaga How about let users pick up what components they want, even batchProcessor if they take the data delay/lost risk, by https://github.com/open-telemetry/opentelemetry-lambda/issues/100 ?

**Comment by anuraaga** [comment]
@wangzlei Making it easy to build a custom collector, especially to choose backends, is important I think, but for core features like processors, which also shouldn't add any significant binary size at all, we should just include them by default.
