### ISSUE TITLE
Migrate Python Lambda instrumentation and resource detector to opentelemetry-python-contrib

### ISSUE THREAD

**Issue by wangzlei** [open-telemetry/opentelemetry-lambda#106]
Now Python's Lambda instrumentation and resource detector are in https://github.com/open-telemetry/opentelemetry-lambda/tree/main/python/src/otel/otel_sdk/opentelemetry
Better to be moved to python-contrib repo

**Comment by NathanielRN** [comment]
Closed in https://github.com/open-telemetry/opentelemetry-python-contrib/pull/777
