### ISSUE TITLE
Adjust collector extension log level

### ISSUE THREAD

**Issue by wangzlei** [open-telemetry/opentelemetry-lambda#108]
All logs in AWS Lambda output to one CloudWatch log group, the collector extension logs will mess up with user's Lambda application logs.

Collector extension should support adjust collector log level. So, user can enable/disable collector log by configuration.

**Comment by vasireddy99** [comment]
Hi @wangzlei,I would like to contribute to this issue, can you please provide more Information on expected solution, should it be something similar to using this [library](https://pkg.go.dev/github.com/alexcesaro/log/stdlog) / [zap](https://github.com/uber-go/zap) and produce logs based on the level such as `info` , `error` .

**Comment by wangzlei** [comment]
@vasireddy99 Also refer to issue https://github.com/open-telemetry/opentelemetry-lambda/issues/230. The otel Lambda extension was originally copied from lambda's sample, it contains some meaningless prints for layer user.

**Comment by goyatparmod** [comment]
We are facing same issue.. Is  their anything being done about it..

**Comment by vasireddy99** [comment]
Implementation to address this issue is currently in progress. Any information regarding that will be updated here in this issue. Thanks for following up.

**Comment by vasireddy99** [comment]
This is tracked at https://github.com/open-telemetry/opentelemetry-lambda/issues/230
