### ISSUE TITLE
Unable to add layer

### ISSUE THREAD

**Issue by geoffhigginbottom** [open-telemetry/opentelemetry-lambda#12]
Been trying to test this but it keeps failing with the following error when I try and attach the layer

not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:eu-west-3:297975325230:layer:opentelemetry-lambda-extension:8

I am using an administrator account with "full access" but it still fails.

Also tried it via the UI and get the same message "You are not authorized to perform: lambda:GetLayerVersion."

Looks like we are not able to query the version of the layer

**Comment by jordanpurinton** [comment]
Can second seeing this behavior.

**Comment by codeboten** [comment]
Hey @geoffhigginbottom, can you try again from one of the 4 regions the layer has been published to and see if it works?

https://github.com/open-telemetry/opentelemetry-lambda/blob/bb143b170e756b922bc0d6788bce6f491c823a00/Makefile#L2

**Comment by geoffhigginbottom** [comment]
Thanks @jordanpurinton but you can only attach a layer from the same region, and I am running in Europe - is there a way to get this published into EU Region please

I get error message "This value must be a valid layer version ARN and in the same region as your function."

**Comment by CathalAherne** [comment]
This is also something we require. I get the same `not authorized error`. My lambda is in eu-west-1. Seems the error message is misleading as this is a region conflict rather than permissions.

Works when adding to a lambda in us-east-1 from same region

**Comment by CathalAherne** [comment]
Also get the same error when using this lambda layer arn:
`arn:aws:lambda:us-east-2:297975325230:layer:opentelemetry-lambda-extension:8`

**Comment by vasireddy99** [comment]
Hi @geoffhigginbotto , Can you please confirm if you are still facing this error. I would like to provide more information/contribute to address this issue.

**Comment by codeboten** [comment]
Closing this issue, please re-open if it continue to be a problem.
