### ISSUE TITLE
Registered auto-instrumentation does not seem to be working for nodejs lambda layer

### ISSUE THREAD

**Issue by longility** [open-telemetry/opentelemetry-lambda#133]
I see that there is instrumentation here: https://github.com/open-telemetry/opentelemetry-lambda/blob/main/nodejs/packages/layer/src/wrapper.ts . 

However, in my x-ray, I don't see the spans for what I'm expecting such as for graphql or dynamodb.

I'm using the lambda layer `arn:aws:lambda:us-east-2:901920570463:layer:aws-otel-nodejs-ver-0-23-0:1`.

I'm not show how to debug this or if this is actually working or not.

**Comment by longility** [comment]
May be related to this https://github.com/open-telemetry/opentelemetry-js-contrib/issues/647

**Comment by davo** [comment]
Question for @longility, seems like your [PR #661](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/661)  solved the problem.

Is this issue still relevant, or should it be closed?

**Comment by longility** [comment]
We can go ahead and close it.
