### ISSUE TITLE
`logger` logs not showing up in Lambda logs

### ISSUE THREAD

**Issue by NathanielRN** [open-telemetry/opentelemetry-lambda#141]
In #138, we were trying to debug an issue related to a missing Python package when we found out that `logger.<level>("log")` logs were not working as [called out in this comment](https://github.com/open-telemetry/opentelemetry-lambda/pull/138#discussion_r698899995_)

Only `print` statements were working. We should fix this so that future debugging is easier.

cc @wangzlei @bhautikpip

**Comment by vasireddy99** [comment]
Looks like the the logging functionality is removed from the functionality, looking at the issue found some interesting [resource](https://www.digitalocean.com/community/tutorials/how-to-use-logging-in-python-3) that might help us. Please provide more detail when you get a chance if the logging needs to be added back. 
I would like to contribute :smiley:

**Comment by NathanielRN** [comment]
I believe this is related to https://github.com/open-telemetry/opentelemetry-python/issues/2594. The fix could be to add `--logs_exporter console` while we wait for the fix upstream.
