### ISSUE TITLE
How to configure B3 Propagator?

### ISSUE THREAD

**Issue by alex-vladut** [open-telemetry/opentelemetry-lambda#18]
First of all, great initiative for putting this AWS Lambda Extension together 👍 Is there any option to configure the propagator to be B3 Propagator?
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md
https://github.com/openzipkin/b3-propagation

**Comment by anuraaga** [comment]
Hey - are you using Java? Currently the agent version supports it but indeed I forgot to add the dependency to the wrapper version, will fix.

For other languages we're still working on scripts but do indent to support extension propagators to make sure interop works well - they would be used when active tracing (i.e., AWS X-Ray) is disabled for the function.

**Comment by alex-vladut** [comment]
Thanks a lot for your prompt answer, sounds great. We're actually JavaScript for our AWS Lambda functions.

**Comment by codeboten** [comment]
hey @alex-vladut, here's an example from the opentelemetry-js repo: https://github.com/open-telemetry/opentelemetry-js/blob/main/examples/tracer-web/examples/xml-http-request/index.js

With additional details here:

https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-propagator-b3

hope this helps!

**Comment by anuraaga** [comment]
Thanks @alex-vladut - we'll be adding layer build scripts here for JavaScript soon, and will make sure to have the propagators available.

**Comment by alex-vladut** [comment]
Nice one, thanks for your help guys 👍

**Comment by serkan-ozal** [comment]
Hi @alex-vladut, glad to hear, it seems that you got what you are looking for.  @tylerbenson should we close this issue?
