### ISSUE TITLE
Lambda extension should be published from an OpenTelemetry aws account

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-lambda#2]
Currently the lambda extension described in the readme is published via a Lightstep-owned account, this should be changed to publish the extension from an OpenTelemetry owned AWS account.

**Comment by vasireddy99** [comment]
Hi @codeboten, Can you please provide more details about the account when you get a chance :-)
. Do we have an OpenTelemetry owned AWS account ? . I would like to contribute and address this issue.

**Comment by tylerbenson** [comment]
Extension and other layers are now published from an OTel AWS account.
