### ISSUE TITLE
Add wangzlei as maintainer

### ISSUE THREAD

**Issue by codeboten** [open-telemetry/opentelemetry-lambda#23]
As per discussion in the SIG meeting on March 24th

**Comment by codeboten** [comment]
@wangzlei I can't seem to find you in the opentelemetry github org, did you accept the invite to join it?

**Comment by wangzlei** [comment]
I saw the invite notification before, but nothing happens after I accept it. @codeboten

**Comment by alolita** [comment]
Thanks @codeboten

**Comment by wangzlei** [comment]
@codeboten Now I am the member of `opentelemetry- CNCF`, could you try to add me as maintainer again?

**Comment by codeboten** [comment]
this is done!

**Comment by wangzlei** [comment]
Excellent! thanks
