### ISSUE TITLE
Delete python/src/otel/Makefile

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-lambda#27]
python/src/otel/Makefile has commands like `yum install` - presumably this isn't for normal use. Do we still need it or can delete?

**Comment by wangzlei** [comment]
OTel Python SDK otlp exporter has to be packaged in Linux, so `run.sh` use `sam build -u` to make sure the makefile is running in docker linux.

https://github.com/open-telemetry/opentelemetry-lambda/blob/main/utils/sam/run.sh#L92

**Comment by wangzlei** [comment]
Since now we use TF to build python layer, the Makefile is no longer required.

**Comment by vasireddy99** [comment]
Thanks you so much for providing more context, referring to these steps in the [README.MD](https://github.com/open-telemetry/opentelemetry-lambda/blob/main/python/README.md). Could there be customers still using the `sam build` for building the layer?
