### ISSUE TITLE
Collector make broken

### ISSUE THREAD

**Issue by imonthercks** [open-telemetry/opentelemetry-lambda#74]
PR #73 caused collector make process to fail.  Currently failing with the following error due to Version and GitHash not being defined.  Was able to back up one commit and build fine.

```
# github.com/open-telemetry/opentelemetry-lambda/collector/lambdacollector
lambdacollector/collector.go:67:14: undefined: Version
lambdacollector/collector.go:68:14: undefined: GitHash
Makefile:18: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by anuraaga** [comment]
Sorry about this - had noticed but forgot to address that the PR build doesn't currently compile the collector will fix that too.
