### ISSUE TITLE
Move python lambda instrumentation and resource detector to `opentelemetry-python-contrib`

### ISSUE THREAD

**Issue by wangzlei** [open-telemetry/opentelemetry-lambda#85]
python lambda instrumentation and Lambda resource detector code is in [opentelemetry-lambda](https://github.com/open-telemetry/opentelemetry-lambda/tree/main/python/src/otel/otel_sdk/opentelemetry), should be moved to [opentelemetry-python-contrib](https://github.com/open-telemetry/opentelemetry-python-contrib)

**Comment by NathanielRN** [comment]
Close when https://github.com/open-telemetry/opentelemetry-python-contrib/pull/739 is merged

**Comment by NathanielRN** [comment]
Same as #106, closing.
