### ISSUE TITLE
Disable class sharing for agent layer

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-lambda#87]
The Java 8 Corretto runtime for Lambda explicitly enables class data sharing. We need to rewrite the JVM command line to append `-Xshare:off` to disable this behavior. Java 11 does not exhibit this problem.

https://stackoverflow.com/questions/65084786/override-jvm-options-in-aws-lambda

**Comment by serkan-ozal** [comment]
Hi @anuraaga,
Why CDS (class data sharing) needs to be disabled in Java 8?

**Comment by serkan-ozal** [comment]
@tylerbenson @rapphil I don't think we need to do something on this? WDYT? Should we close this issue?
