### ISSUE TITLE
Document lack of support for vanilla Java 8 runtime

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-lambda#88]
Our layers don't work on the vanilla, non-corretto Java 8 runtime. This is likely because that runtime uses an old version of Java 8 (if the docs 1.8.0 is to be believed, it's the very first version of Java 8?). We should document we don't support this runtime as customers shouldn't be starting up new functions on a non-corretto runtime anyways.

**Comment by RashmiRam** [comment]
This rescued me from a possible unproductive day. Since Java 8 corretto also has the -Xshare issues, kind of in a fix for sometime.

**Comment by McSick** [comment]
In java8 runtime, collector didnt run with no error messages, collector output, or any indication of incompatibility. We also had problems with java8.al2 runtime as well because of -Xshare issues. Upgrading to java11 made it work.

**Comment by serkan-ozal** [comment]
We have dropped vanilla JDK 8 support. What we should with this issue @tylerbenson @rapphil ?
