### ISSUE TITLE
Add Badges for Code Coverage and CI Status

### ISSUE THREAD

**Issue by kxyr** [open-telemetry/opentelemetry-lambda#93]
**Is your feature request related to a problem?**
Most of the existing OpenTelemetry repositories display a badge for CI status and code coverage. In an effort to have the lambda repository to be up to date and consistent with the other established SDKs and repositories, these badges should be included at the top of the main README.md file.

**Describe the solution you'd like.**
As a developer contributing to OpenTelemetry, I recommend adding a code coverage percentage and CI status badge at the top of the README document of the Lambda repo. These badges are a common feature of many modern open source projects, which improves readability and convenience to developers. By adding a badge to the README.md, with a quick scan, any observer will be able to know the status of the repository.

cc: @alolita

**Comment by anuraaga** [comment]
There isn't any code in this repository only build scripts so we won't add coverage I think. We should add the CI badge though.

**Comment by KKelvinLo** [comment]
> There isn't any code in this repository only build scripts so we won't add coverage I think. We should add the CI badge though.

I see there are 4 different CI workflows (Collector, NodeJS, Java, Terraform) - it wouldn't be sufficient or accurate to add just one badge for multiple builds. Would you suggest adding four badges to the README.md (one for each build)?
